services:
  frontend:
    container_name: client
    build:
      context: .
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ${ENV_FILE}
    # volumes:
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - nginx-network

networks:
  nginx-network:
    name: nginx-network
