FROM golang:1.24-alpine

RUN apk add --no-cache postgresql-client

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV LOG_QUERIES=false
ENV GO_TEST_TIMEOUT=10m

CMD ["sh", "-c", "echo 'Starting integration tests...' && go test -v -timeout $GO_TEST_TIMEOUT ./integration/..."]