FROM golang:1.24-alpine AS builder

RUN go env -w GOCACHE=/go-cache
RUN go env -w GOMODCACHE=/gomod-cache

WORKDIR /build
COPY ["go.sum", "go.mod", "./"]
RUN --mount=type=cache,target=/gomod-cache go mod download
COPY . .
RUN --mount=type=cache,target=/gomod-cache --mount=type=cache,target=/go-cache go build -o migrate cmd/migrate/migrate.go

FROM alpine

WORKDIR /app

COPY --from=builder /build/migrate .

CMD ["./migrate"]